import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
source: https://github.com/Sphinxes0o0/obsidian-persistent-graph
*/`;

const prod = process.argv[2] === "production";

const buildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

if (!prod) {
  buildOptions.watch = true;
}

esbuild.build(buildOptions).catch(() => process.exit(1));
